name: forme_fluent
description: form fields for Fluent UI
version: 2.0.0
homepage: https://github.com/wwwqyhme/forme

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  fluent_ui: ^4.4.1
  flutter:
    sdk: flutter
  forme: ^4.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1